-- https://programmers.co.kr/learn/courses/30/lessons/59044

SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID is null
ORDER BY INS.DATETIME
LIMIT 3